### ISSUE TITLE
Questions about new Proxy functionalities

### ISSUE THREAD

**Issue by Danielosama** [Tibowl/KCCacheProxy#6]
Hello, I had a few questions about the new UI Proxy and its functionalities:

- `Disable browser caching` _This will tell browser to not cache any files_: 
While I understand what this does in theory, what is the practical use? To prevent the browser cache from becoming bloated?

- `Added Bypass checking for gadget updates on gadget server:` _This will stop hammering KC servers each_:
Each.....what? Could you explain in more detail what does this option exactly do?

- `Overwrite game version:` _This can be used to manually overwrite cached game version. Use if you can't enter after maintenance. Can be set to "kca" to fetch KC android version tag._:
If I understand this correctly, this is to update the IP Block bypass, correct? If that is the case, are we supposed to switch to "kca" after a maintenance, and once we have logged in once, back to "false"?

- _You can also change the location to store cache._:
The default cache location is... _default_. Ok, but _where is_ default? Now granted, if you scroll down to the Proxy Log, you can see the path from where the cache is being loaded, but I think it'd be a good idea to put the path to the default location instead of just "default".

And final question, to change the cache location, I reckon we have to copy and paste the new path to it in the white "Cache location" box of the UI. Once that's done, do we have to press `Save` **AND** `Reload cache`, or only one of those?

Thank you for your time and your work.

**Comment by Tibowl** [comment]
> `Disable browser caching` - [...] To prevent the browser cache from becoming bloated?
Yes, it's so other sites aren't affected by KC using up everything. Although, having it enabled is slightly slower since browsers will keep multiple in memory and the proxy will read from disk each time. It was already a functionality in the CLI version, I just added it to the UI version a couple updates ago. (Could also be used for easier hot-swapping of assets, though I don't recommend doing that.)

> `Bypass checking for gadget updates on gadget server`
Oops, guess I didn't finish my sentence in patch notes. Certain assets are marked as "do not cache" on KC servers, so the proxy will still attempt to check those. But if you are behind 403 wall, those will fail anyways, having it enabled will disable those requests to KC. So every game refresh/every 15 minutes (for maint info check) there'll be a useless request going to KC servers.

> `Overwrite game version` - [...] If that is the case, are we supposed to switch to "kca" after a maintenance, and once we have logged in once, back to "false"?
Should be always be kept at false, unless you are having issues with game not updating correctly (eg, can't login after maint/friend fleet button not appearing) (happens when browser got those files cached, proxy should tell browser not to cache those files if 403 got detected, but browser might have them cached when using a VPN). Previous solution was to clear cache of browser, but that might be annoying to do in some viewers. Setting it to kca will fetch every refresh from a file containing android versions, should be set to a number (like A.B.C.D) if false is causing issues since kca will make a request every time you refresh. 

> The default cache location is... default. Ok, but where is default? 
`default` uses userdata folder provided by electron. This is inside some user folder. If the full path gets written to the config file, it'll break when the user gets renamed or the config copied to another computer (with a different username). 

> I reckon we have to copy and paste the new path to it in the white "Cache location" box of the UI.
Yes, I plan on adding a "Open folder" dialogue window later.
> Once that's done, do we have to press `Save` AND `Reload cache`, or only one of those?
Just `Save` is sufficient, it'll automatically reload cache (when `Save` is pressed) when that path is changed. Reload cache is meant for cases where you need to keep the folder the same but still want to reload it (eg, after changing contents of cached.json by overwriting it, or extracted from cache dump).

**Comment by Danielosama** [comment]
I see, thanks for the answers.

> Bypass checking for gadget updates on gadget server
So for foreigners behind the IP Block, it is recommended te keep it on?

And final question, let's say after the next maintenance (on 23/04), I can't log into the game, what would I need to do to update the block bypass? Connect once with VPN like before?

**Comment by Tibowl** [comment]
I've made a [wiki page](https://github.com/Tibowl/KCCacheProxy/wiki/Configuration) yesterday which should answer most questions about settings. It's linked in v2.2.2 in the UI.

> So for foreigners behind the IP Block, it is recommended te keep it on?

Yes

> let's say after the next maintenance (on 23/04), I can't log into the game

Clearing browser cache should be enough. Only if that's impossible/hard to do/preferred not to (if using minimal cache dump), use overwrite game version (with a specific number that you can get by running it with kca once), and if that doesn't work, use VPN. See [that wiki page](https://github.com/Tibowl/KCCacheProxy/wiki/Configuration#overwrite-game-version) for more information.

**Comment by Danielosama** [comment]
> I've made a wiki page yesterday which should answer most questions about settings. It's linked in v2.2.2 in the UI.

Awesome, I'll be closing this Issue then, hopefully everything goes smoothly next maintenance.
